export const hardquestions = [
  {
    question: "Q. Web Crawler is also known as -",
    choice1: "Link crawler",
    choice2: "Search optimizer",
    choice3: "Web Spider",
    choice4: "Web Manager",
    answer: 1,
  },
  {
    question: "Q. Bing is a web search engine owned and operated by -",
    choice1: "Microsoft",
    choice2: "Yahoo",
    choice3: "Alphabet Inc.",
    choice4: "Amazon",
    answer: 1,
  },
  {
    question:
      "Q. Which one of the following is computer high-level programming language?",
    choice1: "COBOL",
    choice2: "PASCAL",
    choice3: "JavaScript",
    choice4: "ALL of the above",
    answer: 4,
  },
  {
    question: "Q. In the field of computer, VIRUS stands for -",
    choice1: "Very Intelligent Result Until Source",
    choice2: "Vital Information Resource Under Siege",
    choice3: "Viral Important Record User Searched",
    choice4: "Very Interchanged Resource Under Search",
    answer: 2,
  },
  {
    question: "Q. Which of the following is not a type of printer?",
    choice1: "Inkjet",
    choice2: "3-D",
    choice3: "Landscape",
    choice4: "Laserjet",
    answer: 3,
  },
  {
    question: "Q. Which of the following is a chat engine?",
    choice1: "Google Bol",
    choice2: "Yahoo Talk",
    choice3: "Ridff Messenger",
    choice4: "None Of the above",
    answer: 4,
  },
  {
    question: "Q. Video conferencing is done through -",
    choice1: "Telephone Network",
    choice2: "IP Network",
    choice3: "TV",
    choice4: "None of the above",
    answer: 2,
  },
];
