export const politics = [
  {
    question: "Q. The members of the Rajya Sabha are elected by",
    choice1: "The People",
    choice2: "Lok Sabha",
    choice3: "elected members of the legislative assembly",
    choice4: "elected members of the legislative council",
    answer: 3,
  },
  {
    question: "Q. The members of the panchayat are",
    choice1: "nominated by the district officer",
    choice2: "the electorates of the respective territorial constituencies",
    choice3: "nominated by local self-government minister of the state",
    choice4: "nominated by the block development organization",
    answer: 2,
  },
  {
    question: "Q. The members of Lok Sabha hold office for a term of",
    choice1: "4 years",
    choice2: "5 years",
    choice3: "6 years",
    choice4: "3years",
    answer: 2,
  },
  {
    question: "Q. The minimum age to qualify for election to the Lok Sabha is",
    choice1: "25 years",
    choice2: "30 years",
    choice3: "40 years",
    choice4: "18 years",
    answer: 1,
  },
  {
    question: "Q. The president can dissolve the Lok Sabha on",
    choice1: "advice of the prime minister",
    choice2: "advice of the chief justice of India",
    choice3: "recommendation of Lok Sabha",
    choice4: "recommendation of the Rajya Sabha",
    answer: 1,
  },
  {
    question: "Q. The members of the Rajya Sabha are elected for a term",
    choice1: "determined by the state legislative assembly of a state",
    choice2: "of five years",
    choice3: "of four years",
    choice4: "of six years",
    answer: 4,
  },
  {
    question: "Q. The members of Lok Sabha are",
    choice1: "directly elected by the people",
    choice2: "indirectly elected",
    choice3: "nominated",
    choice4: "partly elected and partly nominated",
    answer: 1,
  },
];
