export const sports = [
  {
    question: "Q. In which city the 2028 Summer Olympic Games will be organized?",
    choice1: "Amsterdam",
    choice2: "Tokyo",
    choice3: "Mirzapur",
    choice4: "Los Angeles",
    answer: 4,
  },
  {
    question: "Q. Who was the Flag bearer at Rio Olympics-2016 opening ceremony for Indian Contingent?",
    choice1: "Shiv Keshvan",
    choice2: "Neeraj Chopra",
    choice3: "Sushil Kumar",
    choice4: "Abhinav Bindra",
    answer: 4,
  },
  {
    question: "Q. Captain Roop Singh Stadium is related with which sports? (he was a great hockey player)",
    choice1: "Volley Ball",
    choice2: "Cricket",
    choice3: "Athletics",
    choice4: "Hockey",
    answer: 2,
  },
  {
    question: "Q. Which of the following country clinched the ICC under-19 Cricket World Cup?",
    choice1: "India",
    choice2: "South Africa",
    choice3: "Bangladesh",
    choice4: "England",
    answer: 3,
  },
  {
    question: "Q. How many players are there in a team of Volleyball?",
    choice1: "Six",
    choice2: "Five",
    choice3: "Seven",
    choice4: "Eight",
    answer: 1,
  },
 {
    question: "Q. Who won the FIFA world cup 2018",
    choice1: "Spain",
    choice2: "Argentina",
    choice3: "France",
    choice4: "Portugal",
    answer: 3,
  },
 {
    question: "Q. Ballon d'Or honour is associated with the game of -",
    choice1: "Football",
    choice2: "Volleyball",
    choice3: "Dart",
    choice4: "Tennis",
    answer: 1,
  },
];
